INSERT INTO [A1N] VALUES ('GUID', 'int', 32, 0, NULL, 1, NULL, NULL, 0, NULL, 2, NULL, NULL, NULL, 'AB01', NULL, 0, 'KKKKKK');

INSERT INTO [A1N] VALUES ('填报年度', 'int', 4, NULL, NULL, 1, NULL, NULL, 0, 'cyear', NULL, '#>2012 and #<2048', NULL, NULL, 'AB01', NULL, 2, 'YEAR00');

INSERT INTO [A1N] VALUES ('生态站代码', 'nvarchar', 3, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 1, 'AB01', 1, 4, 'SSS000');

INSERT INTO [A1N] VALUES ('年', 'int', 4, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 2, 'AB01', 2, 6, 'YYYY00');

INSERT INTO [A1N] VALUES ('月', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 3, 'AB01', 3, 8, 'MM0000');

INSERT INTO [A1N] VALUES ('日', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB01', NULL, 10, 'DD0000');

INSERT INTO [A1N] VALUES ('样地代码', 'nvarchar', 13, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB01', NULL, 12, 'SSCODE');

INSERT INTO [A1N] VALUES ('样地名称', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB01', NULL, 14, 'SSNAME');

INSERT INTO [A1N] VALUES ('采样分区编号', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB01', NULL, 16, 'PLOTNO');

INSERT INTO [A1N] VALUES ('采样分区描述(微地形)', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB01', NULL, 18, 'PLOTEX');

INSERT INTO [A1N] VALUES ('土壤类型', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB01', NULL, 20, 'STYP00');

INSERT INTO [A1N] VALUES ('母质', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB01', NULL, 22, 'SPAR00');

INSERT INTO [A1N] VALUES ('作物', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB01', NULL, 24, 'CROP00');

INSERT INTO [A1N] VALUES ('采样深度', 'nvarchar', 20, 0, 'cm', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB01', NULL, 26, 'DEPTH0');

INSERT INTO [A1N] VALUES ('样品号', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB01', NULL, 28, 'YPBH00');

INSERT INTO [A1N] VALUES ('交换性钙离子', 'float', 10, 3, 'mmol·kg-1(1/2Ca2+)', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB01', NULL, 30, 'AB0102');

INSERT INTO [A1N] VALUES ('交换性镁离子', 'float', 10, 3, 'mmol·kg-1(1/2 mg2+)', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB01', NULL, 32, 'AB0104');

INSERT INTO [A1N] VALUES ('交换性钾离子', 'float', 10, 3, 'mmol·kg-1 (K+)', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB01', NULL, 34, 'AB0106');

INSERT INTO [A1N] VALUES ('交换性钠离子', 'float', 10, 3, 'mmol·kg-1 (Na+)', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB01', NULL, 36, 'AB0108');

INSERT INTO [A1N] VALUES ('交换性铝离子', 'float', 10, 3, 'mmol·kg-1 (1/3Al3+)', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB01', NULL, 38, 'AB0110');

INSERT INTO [A1N] VALUES ('交换性氢', 'float', 10, 3, 'mmol·kg-1(H+)', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB01', NULL, 40, 'AB0112');

INSERT INTO [A1N] VALUES ('交换性总酸量', 'float', 10, 3, 'mmol·kg-1(+)', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB01', NULL, 42, 'AB0114');

INSERT INTO [A1N] VALUES ('阳离子交换量', 'float', 10, 3, 'mmol·kg(+)', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB01', NULL, 44, 'AB0116');

INSERT INTO [A1N] VALUES ('备注', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB01', NULL, 46, 'MEM000');

INSERT INTO [A1N] VALUES ('GUID', 'int', 32, 0, NULL, 1, NULL, NULL, 0, NULL, 2, NULL, NULL, NULL, 'AB02', NULL, 0, 'KKKKKK');

INSERT INTO [A1N] VALUES ('填报年度', 'int', 4, NULL, NULL, 1, NULL, NULL, 0, 'cyear', NULL, '#>2012 and #<2048', NULL, NULL, 'AB02', NULL, 2, 'YEAR00');

INSERT INTO [A1N] VALUES ('生态站代码', 'nvarchar', 3, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 1, 'AB02', 1, 4, 'SSS000');

INSERT INTO [A1N] VALUES ('年', 'int', 4, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 2, 'AB02', 2, 6, 'YYYY00');

INSERT INTO [A1N] VALUES ('月', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 3, 'AB02', 3, 8, 'MM0000');

INSERT INTO [A1N] VALUES ('日', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB02', NULL, 10, 'DD0000');

INSERT INTO [A1N] VALUES ('样地代码', 'nvarchar', 13, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB02', NULL, 12, 'SSCODE');

INSERT INTO [A1N] VALUES ('样地名称', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB02', NULL, 14, 'SSNAME');

INSERT INTO [A1N] VALUES ('采样分区编号', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB02', NULL, 16, 'PLOTNO');

INSERT INTO [A1N] VALUES ('采样分区描述(微地形)', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB02', NULL, 18, 'PLOTEX');

INSERT INTO [A1N] VALUES ('土壤类型', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB02', NULL, 20, 'STYP00');

INSERT INTO [A1N] VALUES ('母质', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB02', NULL, 22, 'SPAR00');

INSERT INTO [A1N] VALUES ('作物', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB02', NULL, 24, 'CROP00');

INSERT INTO [A1N] VALUES ('采样深度', 'nvarchar', 20, 0, 'cm', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB02', NULL, 26, 'DEPTH0');

INSERT INTO [A1N] VALUES ('样品号', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB02', NULL, 28, 'YPBH00');

INSERT INTO [A1N] VALUES ('土壤有机质', 'float', 10, 3, 'g/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB02', NULL, 30, 'AB0202');

INSERT INTO [A1N] VALUES ('全氮', 'float', 10, 3, 'N g/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB02', NULL, 32, 'AB0204');

INSERT INTO [A1N] VALUES ('全磷', 'float', 10, 3, 'P g/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB02', NULL, 34, 'AB0206');

INSERT INTO [A1N] VALUES ('全钾', 'float', 10, 3, 'K g/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB02', NULL, 36, 'AB0208');

INSERT INTO [A1N] VALUES ('速效氮（碱解氮）', 'float', 10, 3, 'N mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB02', NULL, 38, 'AB0210');

INSERT INTO [A1N] VALUES ('有效磷', 'float', 10, 3, 'P mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB02', NULL, 40, 'AB0212');

INSERT INTO [A1N] VALUES ('速效钾', 'float', 10, 3, 'K mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB02', NULL, 42, 'AB0214');

INSERT INTO [A1N] VALUES ('缓效钾', 'float', 10, 3, 'K mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB02', NULL, 44, 'AB0216');

INSERT INTO [A1N] VALUES ('水溶液提pH值', 'float', 5, 2, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB02', NULL, 46, 'AB0218');

INSERT INTO [A1N] VALUES ('备注', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB02', NULL, 48, 'MEM000');

INSERT INTO [A1N] VALUES ('GUID', 'int', 32, 0, NULL, 1, NULL, NULL, 0, NULL, 2, NULL, NULL, NULL, 'AB03', NULL, 0, 'KKKKKK');

INSERT INTO [A1N] VALUES ('填报年度', 'int', 4, NULL, NULL, 1, NULL, NULL, 0, 'cyear', NULL, '#>2012 and #<2048', NULL, NULL, 'AB03', NULL, 2, 'YEAR00');

INSERT INTO [A1N] VALUES ('生态站代码', 'nvarchar', 3, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 1, 'AB03', 1, 4, 'SSS000');

INSERT INTO [A1N] VALUES ('年', 'int', 4, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 2, 'AB03', 2, 6, 'YYYY00');

INSERT INTO [A1N] VALUES ('月', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 3, 'AB03', 3, 8, 'MM0000');

INSERT INTO [A1N] VALUES ('日', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB03', NULL, 10, 'DD0000');

INSERT INTO [A1N] VALUES ('样地代码', 'nvarchar', 13, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB03', NULL, 12, 'SSCODE');

INSERT INTO [A1N] VALUES ('样地名称', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB03', NULL, 14, 'SSNAME');

INSERT INTO [A1N] VALUES ('采样分区编号', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB03', NULL, 16, 'PLOTNO');

INSERT INTO [A1N] VALUES ('采样分区描述(微地形)', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB03', NULL, 18, 'PLOTEX');

INSERT INTO [A1N] VALUES ('土壤类型', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 20, 'STYP00');

INSERT INTO [A1N] VALUES ('母质', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 22, 'SPAR00');

INSERT INTO [A1N] VALUES ('作物', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 24, 'CROP00');

INSERT INTO [A1N] VALUES ('采样深度', 'nvarchar', 20, 0, 'cm', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 26, 'DEPTH0');

INSERT INTO [A1N] VALUES ('样品号', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 28, 'YPBH00');

INSERT INTO [A1N] VALUES ('硅', 'float', 10, 2, 'SiO2%', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 30, 'AB0302');

INSERT INTO [A1N] VALUES ('铁', 'float', 10, 2, 'Fe2O3%', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 32, 'AB0304');

INSERT INTO [A1N] VALUES ('锰', 'float', 10, 2, 'MnO%', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 34, 'AB0306');

INSERT INTO [A1N] VALUES ('鈦', 'float', 10, 2, 'TiO2%', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 36, 'AB0308');

INSERT INTO [A1N] VALUES ('铝', 'float', 10, 2, 'Al2O3%', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 38, 'AB0310');

INSERT INTO [A1N] VALUES ('钙', 'float', 10, 2, 'CaO%', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 40, 'AB0312');

INSERT INTO [A1N] VALUES ('镁', 'float', 10, 2, 'MgO%', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 42, 'AB0314');

INSERT INTO [A1N] VALUES ('钾', 'float', 10, 2, 'K2O%', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 44, 'AB0316');

INSERT INTO [A1N] VALUES ('钠', 'float', 10, 2, 'Na2O%', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 46, 'AB0318');

INSERT INTO [A1N] VALUES ('磷', 'float', 10, 2, 'P2O5%', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 48, 'AB0320');

INSERT INTO [A1N] VALUES ('烧失量', 'float', 10, 2, 'LOI烧失量%', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 50, 'AB0322');

INSERT INTO [A1N] VALUES ('硫', 'float', 10, 2, 'Sg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 52, 'AB0324');

INSERT INTO [A1N] VALUES ('备注', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB03', NULL, 54, 'MEM000');

INSERT INTO [A1N] VALUES ('GUID', 'int', 32, 0, NULL, 1, NULL, NULL, 0, NULL, 2, NULL, NULL, NULL, 'AB04', NULL, 0, 'KKKKKK');

INSERT INTO [A1N] VALUES ('填报年度', 'int', 4, NULL, NULL, 1, NULL, NULL, 0, 'cyear', NULL, '#>2012 and #<2048', NULL, NULL, 'AB04', NULL, 2, 'YEAR00');

INSERT INTO [A1N] VALUES ('生态站代码', 'nvarchar', 3, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 1, 'AB04', 1, 4, 'SSS000');

INSERT INTO [A1N] VALUES ('年', 'int', 4, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 2, 'AB04', 2, 6, 'YYYY00');

INSERT INTO [A1N] VALUES ('月', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 3, 'AB04', 3, 8, 'MM0000');

INSERT INTO [A1N] VALUES ('日', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB04', NULL, 10, 'DD0000');

INSERT INTO [A1N] VALUES ('样地代码', 'nvarchar', 13, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB04', NULL, 12, 'SSCODE');

INSERT INTO [A1N] VALUES ('样地名称', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB04', NULL, 14, 'SSNAME');

INSERT INTO [A1N] VALUES ('采样分区编号', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB04', NULL, 16, 'PLOTNO');

INSERT INTO [A1N] VALUES ('采样分区描述(微地形)', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB04', NULL, 18, 'PLOTEX');

INSERT INTO [A1N] VALUES ('土壤类型', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 20, 'STYP00');

INSERT INTO [A1N] VALUES ('母质', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 22, 'SPAR00');

INSERT INTO [A1N] VALUES ('作物', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 24, 'CROP00');

INSERT INTO [A1N] VALUES ('采样深度', 'nvarchar', 20, 0, 'cm', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 26, 'DEPTH0');

INSERT INTO [A1N] VALUES ('样品号', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 28, 'YPBH00');

INSERT INTO [A1N] VALUES ('全硼', 'float', 10, 3, 'B mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 30, 'AB0402');

INSERT INTO [A1N] VALUES ('全钼', 'float', 10, 3, 'Mo mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 32, 'AB0404');

INSERT INTO [A1N] VALUES ('全锰', 'float', 10, 3, 'Mn mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 34, 'AB0406');

INSERT INTO [A1N] VALUES ('全锌', 'float', 10, 3, 'Zn mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 36, 'AB0408');

INSERT INTO [A1N] VALUES ('全铜', 'float', 10, 3, 'Cu mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 38, 'AB0410');

INSERT INTO [A1N] VALUES ('全铁', 'float', 10, 3, 'Fe mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 40, 'AB0412');

INSERT INTO [A1N] VALUES ('硒', 'float', 10, 3, 'Se mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 42, 'AB0414');

INSERT INTO [A1N] VALUES ('钴', 'float', 10, 3, 'Co mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 44, 'AB0416');

INSERT INTO [A1N] VALUES ('镉', 'float', 10, 3, 'Cd mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 46, 'AB0418');

INSERT INTO [A1N] VALUES ('铅', 'float', 10, 3, 'Pb mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 48, 'AB0420');

INSERT INTO [A1N] VALUES ('铬', 'float', 10, 3, 'Cr mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 50, 'AB0422');

INSERT INTO [A1N] VALUES ('镍', 'float', 10, 3, 'Ni mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 52, 'AB0424');

INSERT INTO [A1N] VALUES ('汞', 'float', 10, 3, 'Hg mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 54, 'AB0426');

INSERT INTO [A1N] VALUES ('砷', 'float', 10, 3, 'As mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 56, 'AB0428');

INSERT INTO [A1N] VALUES ('备注', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB04', NULL, 58, 'MEM000');

INSERT INTO [A1N] VALUES ('GUID', 'int', 32, 0, NULL, 1, NULL, NULL, 0, NULL, 2, NULL, NULL, NULL, 'AB06', NULL, 0, 'KKKKKK');

INSERT INTO [A1N] VALUES ('填报年度', 'int', 4, NULL, NULL, 1, NULL, NULL, 0, 'cyear', NULL, '#>2012 and #<2048', NULL, NULL, 'AB06', NULL, 2, 'YEAR00');

INSERT INTO [A1N] VALUES ('生态站代码', 'nvarchar', 3, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 1, 'AB06', 1, 4, 'SSS000');

INSERT INTO [A1N] VALUES ('年', 'int', 4, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 2, 'AB06', 2, 6, 'YYYY00');

INSERT INTO [A1N] VALUES ('月', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 3, 'AB06', 3, 8, 'MM0000');

INSERT INTO [A1N] VALUES ('日', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB06', NULL, 10, 'DD0000');

INSERT INTO [A1N] VALUES ('样地代码', 'nvarchar', 13, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB06', NULL, 12, 'SSCODE');

INSERT INTO [A1N] VALUES ('样地名称', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB06', NULL, 14, 'SSNAME');

INSERT INTO [A1N] VALUES ('采样分区编号', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB06', NULL, 16, 'PLOTNO');

INSERT INTO [A1N] VALUES ('采样分区描述(微地形)', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB06', NULL, 18, 'PLOTEX');

INSERT INTO [A1N] VALUES ('处理', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB06', NULL, 20, 'TREAT0');

INSERT INTO [A1N] VALUES ('土壤类型', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB06', NULL, 22, 'STYP00');

INSERT INTO [A1N] VALUES ('母质', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB06', NULL, 24, 'SPAR00');

INSERT INTO [A1N] VALUES ('作物', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB06', NULL, 26, 'CROP00');

INSERT INTO [A1N] VALUES ('采样深度', 'nvarchar', 20, 0, 'cm', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB06', NULL, 28, 'DEPTH0');

INSERT INTO [A1N] VALUES ('样品号', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB06', NULL, 30, 'YPBH00');

INSERT INTO [A1N] VALUES ('硝态氮', 'float', 10, 3, 'mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB06', NULL, 32, 'AB0602');

INSERT INTO [A1N] VALUES ('铵态氮', 'float', 10, 3, 'mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB06', NULL, 34, 'AB0604');

INSERT INTO [A1N] VALUES ('备注', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB06', NULL, 36, 'MEM000');

INSERT INTO [A1N] VALUES ('GUID', 'int', 32, 0, NULL, 1, NULL, NULL, 0, NULL, 2, NULL, NULL, NULL, 'AB07', NULL, 0, 'KKKKKK');

INSERT INTO [A1N] VALUES ('填报年度', 'int', 4, NULL, NULL, 1, NULL, NULL, 0, 'cyear', NULL, '#>2012 and #<2048', NULL, NULL, 'AB07', NULL, 2, 'YEAR00');

INSERT INTO [A1N] VALUES ('生态站代码', 'nvarchar', 3, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 1, 'AB07', 1, 4, 'SSS000');

INSERT INTO [A1N] VALUES ('年', 'int', 4, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 2, 'AB07', 2, 6, 'YYYY00');

INSERT INTO [A1N] VALUES ('月', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 3, 'AB07', 3, 8, 'MM0000');

INSERT INTO [A1N] VALUES ('日', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB07', NULL, 10, 'DD0000');

INSERT INTO [A1N] VALUES ('样地代码', 'nvarchar', 13, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB07', NULL, 12, 'SSCODE');

INSERT INTO [A1N] VALUES ('样地名称', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB07', NULL, 14, 'SSNAME');

INSERT INTO [A1N] VALUES ('采样分区编号', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB07', NULL, 16, 'PLOTNO');

INSERT INTO [A1N] VALUES ('采样分区描述(微地形)', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB07', NULL, 18, 'PLOTEX');

INSERT INTO [A1N] VALUES ('土壤类型', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 20, 'STYP00');

INSERT INTO [A1N] VALUES ('母质', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 22, 'SPAR00');

INSERT INTO [A1N] VALUES ('作物', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 24, 'CROP00');

INSERT INTO [A1N] VALUES ('采样深度', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 26, 'DEPTH0');

INSERT INTO [A1N] VALUES ('样品号', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 28, 'YPBH00');

INSERT INTO [A1N] VALUES ('有效铁', 'float', 10, 3, 'Fe mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 30, 'AB0702');

INSERT INTO [A1N] VALUES ('有效铁分析方法', 'nvarchar', 80, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 32, 'AB0703');

INSERT INTO [A1N] VALUES ('有效铜', 'float', 10, 3, 'Cu mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 34, 'AB0704');

INSERT INTO [A1N] VALUES ('有效铜分析方法', 'nvarchar', 80, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 36, 'AB0705');

INSERT INTO [A1N] VALUES ('有效钼', 'float', 10, 3, 'Mo mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 38, 'AB0706');

INSERT INTO [A1N] VALUES ('有效钼分析方法', 'nvarchar', 80, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 40, 'AB0707');

INSERT INTO [A1N] VALUES ('有效硼', 'float', 10, 3, 'B mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 42, 'AB0708');

INSERT INTO [A1N] VALUES ('有效硼分析方法', 'nvarchar', 80, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 44, 'AB0709');

INSERT INTO [A1N] VALUES ('有效锰', 'float', 10, 3, 'Mn mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 46, 'AB0710');

INSERT INTO [A1N] VALUES ('有效锰分析方法', 'nvarchar', 80, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 48, 'AB0711');

INSERT INTO [A1N] VALUES ('有效锌', 'float', 10, 3, 'Zn mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 50, 'AB0712');

INSERT INTO [A1N] VALUES ('有效锌分析方法', 'nvarchar', 80, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 52, 'AB0713');

INSERT INTO [A1N] VALUES ('有效硫', 'float', 10, 3, 'P mg/kg', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 54, 'AB0714');

INSERT INTO [A1N] VALUES ('有效硫分析方法', 'nvarchar', 80, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 56, 'AB0715');

INSERT INTO [A1N] VALUES ('备注', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB07', NULL, 58, 'MEM000');

INSERT INTO [A1N] VALUES ('GUID', 'int', 32, 0, NULL, 1, NULL, NULL, 0, NULL, 2, NULL, NULL, NULL, 'AB08', NULL, 0, 'KKKKKK');

INSERT INTO [A1N] VALUES ('填报年度', 'int', 4, NULL, NULL, 1, NULL, NULL, 0, 'cyear', NULL, '#>2012 and #<2048', NULL, NULL, 'AB08', NULL, 2, 'YEAR00');

INSERT INTO [A1N] VALUES ('生态站代码', 'nvarchar', 3, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 1, 'AB08', 1, 4, 'SSS000');

INSERT INTO [A1N] VALUES ('年', 'int', 4, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 2, 'AB08', 2, 6, 'YYYY00');

INSERT INTO [A1N] VALUES ('月', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 3, 'AB08', 3, 8, 'MM0000');

INSERT INTO [A1N] VALUES ('日', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB08', NULL, 10, 'DD0000');

INSERT INTO [A1N] VALUES ('样地代码', 'nvarchar', 13, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB08', NULL, 12, 'SSCODE');

INSERT INTO [A1N] VALUES ('样地名称', 'nvarchar', 60, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB08', NULL, 14, 'SSNAME');

INSERT INTO [A1N] VALUES ('采样分区编号', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB08', NULL, 16, 'PLOTNO');

INSERT INTO [A1N] VALUES ('采样分区描述(微地形)', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB08', NULL, 18, 'PLOTEX');

INSERT INTO [A1N] VALUES ('土壤类型', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB08', NULL, 20, 'STYP00');

INSERT INTO [A1N] VALUES ('母质', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB08', NULL, 22, 'SPAR00');

INSERT INTO [A1N] VALUES ('作物', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB08', NULL, 24, 'CROP00');

INSERT INTO [A1N] VALUES ('采样深度', 'nvarchar', 20, 0, 'cm', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB08', NULL, 26, 'DEPTH0');

INSERT INTO [A1N] VALUES ('样品号', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB08', NULL, 28, 'YPBH00');

INSERT INTO [A1N] VALUES ('2-0.05mm砂粒百分率', 'float', 10, 3, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB08', NULL, 30, 'AB0802');

INSERT INTO [A1N] VALUES ('0.05-0.002mm粉粒百分率', 'float', 10, 3, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB08', NULL, 32, 'AB0804');

INSERT INTO [A1N] VALUES ('小于0.002mm粘粒百分率', 'float', 10, 3, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB08', NULL, 34, 'AB0806');

INSERT INTO [A1N] VALUES ('土壤质地名称', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB08', NULL, 36, 'AB0808');

INSERT INTO [A1N] VALUES ('亚类', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB16', NULL, 24, 'AB1608');

INSERT INTO [A1N] VALUES ('母质', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB16', NULL, 26, 'SPAR00');

INSERT INTO [A1N] VALUES ('植被类型', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB16', NULL, 28, 'CROP00');

INSERT INTO [A1N] VALUES ('样品号', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB16', NULL, 30, 'YPBH00');

INSERT INTO [A1N] VALUES ('层次名称', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB16', NULL, 32, 'AB1610');

INSERT INTO [A1N] VALUES ('土层深度', 'nvarchar', 40, 0, 'cm', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB16', NULL, 34, 'AB1612');

INSERT INTO [A1N] VALUES ('土层间过渡明显程度', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB16', NULL, 36, 'AB1614');

INSERT INTO [A1N] VALUES ('土层间过渡形式', 'nvarchar', 60, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB16', NULL, 38, 'AB1616');

INSERT INTO [A1N] VALUES ('形态描述', 'nvarchar', 80, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB16', NULL, 40, 'AB1618');

INSERT INTO [A1N] VALUES ('备注', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB16', NULL, 42, 'MEM000');

INSERT INTO [A1N] VALUES ('GUID', 'int', 32, 0, NULL, 1, NULL, NULL, 0, NULL, 2, NULL, NULL, NULL, 'AB17', NULL, 0, 'KKKKKK');

INSERT INTO [A1N] VALUES ('填报年度', 'int', 4, NULL, NULL, 1, NULL, NULL, 0, 'cyear', NULL, '#>2012 and #<2048', NULL, NULL, 'AB17', NULL, 2, 'YEAR00');

INSERT INTO [A1N] VALUES ('生态站代码', 'nvarchar', 3, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 1, 'AB17', 1, 4, 'SSS000');

INSERT INTO [A1N] VALUES ('年', 'int', 4, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 2, 'AB17', 2, 6, 'YYYY00');

INSERT INTO [A1N] VALUES ('月', 'int', 2, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, 1, 3, 'AB17', 3, 8, 'MM0000');

INSERT INTO [A1N] VALUES ('日', 'int', 2, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB17', NULL, 10, 'DD0000');

INSERT INTO [A1N] VALUES ('样地代码', 'nvarchar', 13, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB17', NULL, 12, 'SSCODE');

INSERT INTO [A1N] VALUES ('样地名称', 'nvarchar', 100, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB17', NULL, 14, 'SSNAME');

INSERT INTO [A1N] VALUES ('采样点编号', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB17', NULL, 16, 'PLOTNO');

INSERT INTO [A1N] VALUES ('采样点描述', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB17', NULL, 18, 'PLOTEX');

INSERT INTO [A1N] VALUES ('土壤类型', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB17', NULL, 20, 'STYP00');

INSERT INTO [A1N] VALUES ('母质', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB17', NULL, 22, 'SPAR00');

INSERT INTO [A1N] VALUES ('植被(或群落)', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB17', NULL, 24, 'CROP00');

INSERT INTO [A1N] VALUES ('采样深度(cm)', 'float', 20, 3, 'cm', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB17', NULL, 26, 'DEPTH0');

INSERT INTO [A1N] VALUES ('样品号', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB17', NULL, 28, 'YPBH00');

INSERT INTO [A1N] VALUES ('溶解有机碳', 'float', 10, 3, 'C mg/L', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB17', NULL, 30, 'AB1702');

INSERT INTO [A1N] VALUES ('标准差', 'float', 8, 2, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB17', NULL, 32, 'AB1704');

INSERT INTO [A1N] VALUES ('重复数', 'int', 4, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB17', NULL, 34, 'AB1706');

INSERT INTO [A1N] VALUES ('备注', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB17', NULL, 36, 'MEM000');

INSERT INTO [A1N] VALUES ('GUID', 'int', 32, 0, NULL, 1, NULL, NULL, 0, NULL, 2, NULL, NULL, NULL, 'ABMethod', NULL, 0, 'KKKKKK');

INSERT INTO [A1N] VALUES ('填报年度', 'int', 4, NULL, NULL, 1, NULL, NULL, 0, 'cyear', NULL, '#>2012 and #<2048', NULL, NULL, 'ABMethod', NULL, 2, 'YEAR00');

INSERT INTO [A1N] VALUES ('生态站代码', 'nvarchar', 3, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 1, 'ABMethod', 1, 4, 'SSS000');

INSERT INTO [A1N] VALUES ('年', 'int', 4, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 1, 'ABMethod', 1, 6, 'YYYY00');

INSERT INTO [A1N] VALUES ('表代码', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'ABMethod', NULL, 8, 'T_CODE');

INSERT INTO [A1N] VALUES ('表名称', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'ABMethod', NULL, 10, 'T_NAME');

INSERT INTO [A1N] VALUES ('分析项目名称', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'ABMethod', NULL, 12, 'VAR_NAME');

INSERT INTO [A1N] VALUES ('分析方法名称', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'ABMethod', NULL, 14, 'VAR_METHOD');

INSERT INTO [A1N] VALUES ('参照国标名称', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'ABMethod', NULL, 16, 'VAR_STANDARD');

INSERT INTO [A1N] VALUES ('备注', 'nvarchar', 80, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'ABMethod', NULL, 18, 'MEM000');

INSERT INTO [A1N] VALUES ('备注', 'nvarchar', 60, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB08', NULL, 38, 'MEM000');

INSERT INTO [A1N] VALUES ('GUID', 'int', 32, 0, NULL, 1, NULL, NULL, 0, NULL, 2, NULL, NULL, NULL, 'AB09', NULL, 0, 'KKKKKK');

INSERT INTO [A1N] VALUES ('填报年度', 'int', 4, NULL, NULL, 1, NULL, NULL, 0, 'cyear', NULL, '#>2012 and #<2048', NULL, NULL, 'AB09', NULL, 2, 'YEAR00');

INSERT INTO [A1N] VALUES ('生态站代码', 'nvarchar', 3, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 1, 'AB09', 1, 4, 'SSS000');

INSERT INTO [A1N] VALUES ('年', 'int', 4, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 2, 'AB09', 2, 6, 'YYYY00');

INSERT INTO [A1N] VALUES ('月', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 3, 'AB09', 3, 8, 'MM0000');

INSERT INTO [A1N] VALUES ('日', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB09', NULL, 10, 'DD0000');

INSERT INTO [A1N] VALUES ('样地代码', 'nvarchar', 13, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB09', NULL, 12, 'SSCODE');

INSERT INTO [A1N] VALUES ('样地名称', 'nvarchar', 60, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB09', NULL, 14, 'SSNAME');

INSERT INTO [A1N] VALUES ('采样分区编号', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB09', NULL, 16, 'PLOTNO');

INSERT INTO [A1N] VALUES ('采样分区描述(微地形)', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB09', NULL, 18, 'PLOTEX');

INSERT INTO [A1N] VALUES ('土壤类型', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB09', NULL, 20, 'STYP00');

INSERT INTO [A1N] VALUES ('母质', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB09', NULL, 22, 'SPAR00');

INSERT INTO [A1N] VALUES ('作物', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB09', NULL, 24, 'CROP00');

INSERT INTO [A1N] VALUES ('采样深度', 'nvarchar', 20, 0, 'cm', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB09', NULL, 26, 'DEPTH0');

INSERT INTO [A1N] VALUES ('样品号', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB09', NULL, 28, 'YPBH00');

INSERT INTO [A1N] VALUES ('土壤容重平均值', 'float', 10, 3, 'g/m3', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB09', NULL, 30, 'AB0902');

INSERT INTO [A1N] VALUES ('均方差', 'float', 10, 3, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB09', NULL, 32, 'AB0904');

INSERT INTO [A1N] VALUES ('样本数', 'int', 4, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB09', NULL, 34, 'AB0906');

INSERT INTO [A1N] VALUES ('备注', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB09', NULL, 36, 'MEM000');

INSERT INTO [A1N] VALUES ('GUID', 'int', 32, 0, NULL, 1, NULL, NULL, 0, NULL, 2, NULL, NULL, NULL, 'AB10', NULL, 0, 'KKKKKK');

INSERT INTO [A1N] VALUES ('填报年度', 'int', 4, NULL, NULL, 1, NULL, NULL, 0, 'cyear', NULL, '#>2012 and #<2048', NULL, NULL, 'AB10', NULL, 2, 'YEAR00');

INSERT INTO [A1N] VALUES ('生态站代码', 'nvarchar', 3, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 1, 'AB10', 1, 4, 'SSS000');

INSERT INTO [A1N] VALUES ('年', 'int', 4, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 2, 'AB10', 2, 6, 'YYYY00');

INSERT INTO [A1N] VALUES ('月', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 3, 'AB10', 3, 8, 'MM0000');

INSERT INTO [A1N] VALUES ('日', 'int', 2, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB10', NULL, 10, 'DD0000');

INSERT INTO [A1N] VALUES ('样地代码', 'nvarchar', 13, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB10', NULL, 12, 'SSCODE');

INSERT INTO [A1N] VALUES ('样地名称', 'nvarchar', 60, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB10', NULL, 14, 'SSNAME');

INSERT INTO [A1N] VALUES ('采样分区编号', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB10', NULL, 16, 'PLOTNO');

INSERT INTO [A1N] VALUES ('采样分区描述(微地形)', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB10', NULL, 18, 'PLOTEX');

INSERT INTO [A1N] VALUES ('土壤类型', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB10', NULL, 20, 'STYP00');

INSERT INTO [A1N] VALUES ('母质', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB10', NULL, 22, 'SPAR00');

INSERT INTO [A1N] VALUES ('作物', 'nvarchar', 20, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB10', NULL, 24, 'CROP00');

INSERT INTO [A1N] VALUES ('采样深度', 'nvarchar', 20, 0, 'cm', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB10', NULL, 26, 'DEPTH0');

INSERT INTO [A1N] VALUES ('样品号', 'nvarchar', 40, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB10', NULL, 28, 'YPBH00');

INSERT INTO [A1N] VALUES ('碳酸根', 'float', 10, 3, 'cmol·kg-1(1/2CO2-3)', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB10', NULL, 30, 'AB1002');

INSERT INTO [A1N] VALUES ('重碳酸根', 'float', 10, 3, 'cmol·kg-1(HCO-3)', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB10', NULL, 32, 'AB1004');

INSERT INTO [A1N] VALUES ('硫酸根', 'float', 10, 3, 'cmol·kg-1(SO2-4)', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB10', NULL, 34, 'AB1006');

INSERT INTO [A1N] VALUES ('氯根', 'float', 10, 3, 'cmol·kg-1(Cl-)', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB10', NULL, 36, 'AB1008');

INSERT INTO [A1N] VALUES ('钙离子', 'float', 10, 3, 'cmol·kg-1(1/2Ca2+)', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB10', NULL, 38, 'AB1010');

INSERT INTO [A1N] VALUES ('镁离子', 'float', 10, 3, 'cmol·kg-1(1/2 mg2+)', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB10', NULL, 40, 'AB1012');

INSERT INTO [A1N] VALUES ('钾离子', 'float', 10, 3, 'cmol·kg-1 (K+)', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB10', NULL, 42, 'AB1014');

INSERT INTO [A1N] VALUES ('钠离子', 'float', 10, 3, 'cmol·kg-1 (Na+)', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB10', NULL, 44, 'AB1016');

INSERT INTO [A1N] VALUES ('全盐量', 'float', 10, 3, '%', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB10', NULL, 46, 'AB1018');

INSERT INTO [A1N] VALUES ('电导率', 'float', 10, 3, 'ms/cm', 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB10', NULL, 48, 'AB1020');

INSERT INTO [A1N] VALUES ('备注', 'nvarchar', 40, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB10', NULL, 50, 'MEM000');

INSERT INTO [A1N] VALUES ('GUID', 'int', 32, 0, NULL, 1, NULL, NULL, 0, NULL, 2, NULL, NULL, NULL, 'AB16', NULL, 0, 'KKKKKK');

INSERT INTO [A1N] VALUES ('填报年度', 'int', 4, NULL, NULL, 1, NULL, NULL, 0, 'cyear', NULL, '#>2012 and #<2048', NULL, NULL, 'AB16', NULL, 2, 'YEAR00');

INSERT INTO [A1N] VALUES ('生态站代码', 'nvarchar', 3, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, 1, 'AB16', 1, 4, 'SSS000');

INSERT INTO [A1N] VALUES ('年', 'int', 4, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, 1, 2, 'AB16', 2, 6, 'YYYY00');

INSERT INTO [A1N] VALUES ('月', 'int', 2, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, 1, 3, 'AB16', 3, 8, 'MM0000');

INSERT INTO [A1N] VALUES ('日', 'int', 2, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB16', NULL, 10, 'DD0000');

INSERT INTO [A1N] VALUES ('样地代码', 'nvarchar', 13, 0, NULL, 1, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB16', NULL, 12, 'SSCODE');

INSERT INTO [A1N] VALUES ('样地名称', 'nvarchar', 100, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB16', NULL, 14, 'SSNAME');

INSERT INTO [A1N] VALUES ('剖面地点', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB16', NULL, 16, 'AB1602');

INSERT INTO [A1N] VALUES ('剖面地点经度', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, 1, NULL, 'AB16', NULL, 18, 'AB1604');

INSERT INTO [A1N] VALUES ('剖面地点纬度', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB16', NULL, 20, 'AB1606');

INSERT INTO [A1N] VALUES ('土类', 'nvarchar', 20, 0, NULL, 0, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 'AB16', NULL, 22, 'STYP00');

